{
		"name": "EdX-curso via plataforma web, Universidad MIT",
		"location": "bdeh",
		"latitude": 48.74,
		"longitude": 1.37,
		"textPopUpMap": "hdeiwi",
		"colorCircleGraph": "rgb(154,42,7)",
		"colorCircleStrokeGraph": "rgb(200,200,200)",
		"degree": "2 meses de formación en Python",
		"majors": ["major1", "major2", "major3"],
		"dates": "October 15, 2014",
		"positionAxeY": 60,
		"onlineOrSchool": "online",
		"url": "https://www.edx.org/"
	},
